[tool.poetry]
name = "1"
version = "0.1.0"
description = "dz"
authors = ["Polina Dyka"]
readme = "README.md"

[tool.poetry.dependencies]
python = "3.10.8"
Jinja2 = "^3.1.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
